<?php
/** @var \BVMyBlog\Blog\Block\LastPosts $block*/

$data = $block->getTopBlogs();
$match = $block->isMatch();
?>
<div>
    <?php if ($match): ?>
    <h3><?= $block->escapeHtml(__('Last 5 posts:')) ?></h3>
        <ul>
            <?php foreach ($data as $value):
                $item = $value->getTitle();
                $id = $value->getId();?>
                <li><a href='<?= $block->escapeHtml($block->getUrlById($id))?>'>
                        <?= $block->escapeHtml($item) ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>