<?php
/** @var \BVMyBlog\Blog\Block\LastPosts $block*/

$data = $block->getTopBlogs();
$match = $block->isMatch();
?>
<div class="blog-div-head">
    <?php if ($match): ?>
    <h2><?= $block->escapeHtml(__('Last 5 posts:')) ?></h2>
        <ul>
            <?php foreach ($data as $value):
                $item = $value->getTitle();
                $id = $value->getPostId();?>
                <li><a href='<?= $block->escapeUrl($block->getUrlById($id))?>'>
                        <?= $block->escapeHtml($item) ?></a></li>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>