<?php
/** @var \BVMyBlog\Blog\Block\Top $block*/
/** @var \BVMyBlog\Blog\ViewModel\Top $topViewModel */

$topViewModel = $block->getData('top_view_model');
$data = $topViewModel->listTop()->getData();
$match = $topViewModel->isMatch();
?>
<div>
    <?php if ($match): ?>
    <h3>Last 5 posts:</h3>
        <ul>
            <?php foreach ($data as $value):
                $item = $value['name'];
                $id = $value['post_id'];?>
                <?= /* @noEscape */ "<li><a href='myblog/index/index?id=$id'>$item</a></li>" ?>
            <?php endforeach; ?>
        </ul>
    <?php endif; ?>
</div>